/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package suporte.view;

import exceptions.DadoInvalidoException;
import exceptions.ErroInternoException;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import main.Fachada;
import tweet.Tweet;
import utilitarios.ArquivoUtils;

/**
 *
 * @author Arthur
 */
public class UnirArquivosView extends javax.swing.JDialog {

    private TableModelUnirArquivos tableModel;
    private final ArrayList<Tweet> tweets;

    /**
     * Creates new form JuntarArquivosView
     *
     * @param parent
     * @param modal
     */
    public UnirArquivosView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setarTableModel();
        tweets = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPUnir = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTUnir = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLNum = new javax.swing.JLabel();
        jXBAdicionar = new org.jdesktop.swingx.JXButton();
        jXBSalvar = new org.jdesktop.swingx.JXButton();
        jXBCancelar = new org.jdesktop.swingx.JXButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Unir arquivos");

        jPUnir.setBackground(new java.awt.Color(255, 255, 255));

        jTUnir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTUnir);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Número de tweets:");

        jLNum.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLNum.setForeground(new java.awt.Color(102, 102, 255));

        jXBAdicionar.setBackground(new java.awt.Color(255, 255, 255));
        jXBAdicionar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jXBAdicionar.setText("Adicionar");
        jXBAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXBAdicionarActionPerformed(evt);
            }
        });

        jXBSalvar.setBackground(new java.awt.Color(255, 255, 255));
        jXBSalvar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jXBSalvar.setText("Salvar");
        jXBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXBSalvarActionPerformed(evt);
            }
        });

        jXBCancelar.setBackground(new java.awt.Color(255, 255, 255));
        jXBCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jXBCancelar.setText("Cancelar");
        jXBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXBCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPUnirLayout = new javax.swing.GroupLayout(jPUnir);
        jPUnir.setLayout(jPUnirLayout);
        jPUnirLayout.setHorizontalGroup(
            jPUnirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPUnirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPUnirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPUnirLayout.createSequentialGroup()
                        .addComponent(jXBAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLNum, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPUnirLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jXBSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209))
        );

        jPUnirLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jXBCancelar, jXBSalvar});

        jPUnirLayout.setVerticalGroup(
            jPUnirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPUnirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPUnirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLNum, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPUnirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jXBAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPUnirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXBSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPUnirLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLNum, jLabel1});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPUnir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPUnir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jXBAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXBAdicionarActionPerformed
        unirArquivos();
    }//GEN-LAST:event_jXBAdicionarActionPerformed

    private void jXBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXBCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jXBCancelarActionPerformed

    private void jXBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXBSalvarActionPerformed
        try {
            File arquivo = ArquivoUtils.abrirFileChooserSalvarArquivo(".txt");
            Fachada.getINSTANCIA().inserirTweets(arquivo, this.tweets);
            JOptionPane.showMessageDialog(null, "Arquivos unidos com sucesso!");
            this.dispose();
        } catch (ErroInternoException ex) {
            ex.exibirMensagemAoUsuario(ex);
        } catch (ArquivoUtils.ArquivoNaoSalvoException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jXBSalvarActionPerformed

    private void unirArquivos() {
        try {
            File[] files = ArquivoUtils.selecionarArquivos();
            for (File file : files) {
                ArrayList<Tweet> tweetsRecuperados = Fachada.getINSTANCIA().recuperarTweets(file);
                this.tweets.addAll(tweetsRecuperados);
                jLNum.setText(String.valueOf(this.tweets.size()));
                this.tableModel.addRow(this.tableModel.new Arquivo(file.getAbsolutePath(), tweetsRecuperados.size()));
            }
        }  catch (ErroInternoException ex) {
            ex.exibirMensagemAoUsuario(ex);
        } catch (DadoInvalidoException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (ArquivoUtils.ArquivoNaoSelecionadoException ex) {
            System.err.println(ex.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnirArquivosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnirArquivosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnirArquivosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnirArquivosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            UnirArquivosView dialog = new UnirArquivosView(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLNum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPUnir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTUnir;
    private org.jdesktop.swingx.JXButton jXBAdicionar;
    private org.jdesktop.swingx.JXButton jXBCancelar;
    private org.jdesktop.swingx.JXButton jXBSalvar;
    // End of variables declaration//GEN-END:variables

    private void setarTableModel() {
        tableModel = new TableModelUnirArquivos(jTUnir);
        jTUnir.setModel(tableModel);
        jTUnir.getColumnModel().getColumn(0).setPreferredWidth(400);
        jTUnir.getColumnModel().getColumn(1).setPreferredWidth(100);
    }

    public class TableModelUnirArquivos extends utilitarios.ModeloDeTabelaAbstrato {

        private final String[] colunas = new String[]{"Arquivo", "Nº Tweets"};

        public TableModelUnirArquivos(JTable tabela) {
            super(tabela);
        }

        @Override
        public int getColumnCount() {
            return this.colunas.length;
        }

        @Override
        public String getColumnName(int column) {
            return this.colunas[column];
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Arquivo arq = (Arquivo) this.lista.get(rowIndex);
            switch (columnIndex) {
                case 0:
                    return arq.getArquivo();
                case 1:
                    return arq.getNumTweets();
                default:
                    throw new IndexOutOfBoundsException();
            }
        }

        public class Arquivo {

            private String arquivo;
            private Integer numTweets;

            public Arquivo(String arquivo, Integer numTweets) {
                this.arquivo = arquivo;
                this.numTweets = numTweets;
            }

            public String getArquivo() {
                return arquivo;
            }

            public void setArquivo(String arquivo) {
                this.arquivo = arquivo;
            }

            public Integer getNumTweets() {
                return numTweets;
            }

            public void setNumTweets(Integer numTweets) {
                this.numTweets = numTweets;
            }

        }
    }
}
