/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pre_processamento;

import capturador.view.TableModelTabelaTermos;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author W8
 */
public class PreProcessamentoView extends javax.swing.JDialog {

    private final TableModelTabelaTermos tableTermos;

    /**
     * Creates new form PreProcessamentoView
     *
     * @param parent
     * @param modal
     */
    public PreProcessamentoView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        verificarNumeroCaracteresRestantes();
        jTFTermo.setDocument(new utilitarios.LimitaNroCaracteres(140));
        tableTermos = new TableModelTabelaTermos(jXTTermos);
        jXTTermos.setModel(tableTermos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPPreProcessamento = new javax.swing.JPanel();
        jRBRemDuplicados = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLTermo = new javax.swing.JLabel();
        jTFTermo = new javax.swing.JTextField();
        jLNumChar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jXTTermos = new org.jdesktop.swingx.JXTable();
        jXBPreProcessar = new org.jdesktop.swingx.JXButton();
        jXBSair = new org.jdesktop.swingx.JXButton();
        jLabel1 = new javax.swing.JLabel();
        jLArquivo = new javax.swing.JLabel();
        jRBRemRT = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPPreProcessamento.setBackground(new java.awt.Color(255, 255, 255));

        jRBRemDuplicados.setBackground(new java.awt.Color(255, 255, 255));
        jRBRemDuplicados.setText("Remover dados duplicados");
        jRBRemDuplicados.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jRBRemDuplicados.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Remover termos"));

        jLTermo.setText("Termo:");

        jTFTermo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFTermoFocusGained(evt);
            }
        });
        jTFTermo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFTermoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFTermoKeyReleased(evt);
            }
        });

        jLNumChar.setForeground(new java.awt.Color(51, 102, 255));
        jLNumChar.setText("140");

        jXTTermos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jXTTermos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jXTTermosKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jXTTermos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLTermo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFTermo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLNumChar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTermo)
                    .addComponent(jTFTermo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNumChar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );

        jXBPreProcessar.setBackground(new java.awt.Color(255, 255, 255));
        jXBPreProcessar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jXBPreProcessar.setText("Pré-processar");
        jXBPreProcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXBPreProcessarActionPerformed(evt);
            }
        });

        jXBSair.setBackground(new java.awt.Color(255, 255, 255));
        jXBSair.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jXBSair.setText("Sair");
        jXBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXBSairActionPerformed(evt);
            }
        });

        jLabel1.setText("Arquivo:");

        jLArquivo.setText("jLabel2");

        jRBRemRT.setBackground(new java.awt.Color(255, 255, 255));
        jRBRemRT.setText("Remover retweets");

        javax.swing.GroupLayout jPPreProcessamentoLayout = new javax.swing.GroupLayout(jPPreProcessamento);
        jPPreProcessamento.setLayout(jPPreProcessamentoLayout);
        jPPreProcessamentoLayout.setHorizontalGroup(
            jPPreProcessamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPreProcessamentoLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jXBPreProcessar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXBSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(237, Short.MAX_VALUE))
            .addGroup(jPPreProcessamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPreProcessamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPPreProcessamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPPreProcessamentoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPPreProcessamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRBRemRT)
                            .addComponent(jRBRemDuplicados))))
                .addGap(22, 22, 22))
        );

        jPPreProcessamentoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jXBPreProcessar, jXBSair});

        jPPreProcessamentoLayout.setVerticalGroup(
            jPPreProcessamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPreProcessamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPPreProcessamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLArquivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jRBRemRT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRBRemDuplicados)
                .addGap(8, 8, 8)
                .addGroup(jPPreProcessamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXBPreProcessar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXBSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPPreProcessamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPPreProcessamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFTermoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFTermoFocusGained
        jTFTermo.selectAll();
    }//GEN-LAST:event_jTFTermoFocusGained

    private void jTFTermoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFTermoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTFTermo.requestFocus();
            adicionarTermo(jTFTermo.getText());
            jTFTermo.setText("");
        }
    }//GEN-LAST:event_jTFTermoKeyPressed

    private void jTFTermoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFTermoKeyReleased
        verificarNumeroCaracteresRestantes();
    }//GEN-LAST:event_jTFTermoKeyReleased

    private void jXTTermosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jXTTermosKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            Object[] options = new Object[]{"Sim", "Não"};
            int r = JOptionPane.showOptionDialog(null, "Deseja excluir o termo " + tableTermos.getTermo(jXTTermos.getSelectedRow()) + "?", "Confirmação",
                    JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, 0);
            if (r == 0) {
                tableTermos.removeRow(jXTTermos.getSelectedRow());
            }
        }
    }//GEN-LAST:event_jXTTermosKeyPressed

    private void jXBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXBSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jXBSairActionPerformed

    private void jXBPreProcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXBPreProcessarActionPerformed
        try {
            ArrayList<String> tweetsPreProcessados = PreProcessamento.getINSTANCIA().preProcessar(PreProcessamento.getINSTANCIA().getArquivo(), jRBRemDuplicados.isSelected(), jRBRemRT.isSelected(), tableTermos.getTermos());
            PreProcessamento.getINSTANCIA().salvarTweetsPreProcessados(tweetsPreProcessados);
            JOptionPane.showMessageDialog(null, "Arquivo salvo: Dados pré-processados com sucesso!", "Informação do sistema", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(PreProcessamentoView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
    }//GEN-LAST:event_jXBPreProcessarActionPerformed

    private void verificarNumeroCaracteresRestantes() {
        String termo = jTFTermo.getText();
        int tam = termo.length();
        int restante = 140 - tam;
        jLNumChar.setText(String.valueOf(restante));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PreProcessamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PreProcessamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PreProcessamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreProcessamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            PreProcessamentoView dialog = new PreProcessamentoView(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    private void adicionarTermo(String termo) {
        if (!termo.isEmpty()) {
            tableTermos.addRow(termo);
        } else {
            JOptionPane.showMessageDialog(null, "Informe o termo!", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }

    public void abrirTelaComArquivoParaProcessamento(File arquivo) {
        jLArquivo.setText(arquivo.getAbsolutePath());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLArquivo;
    private javax.swing.JLabel jLNumChar;
    private javax.swing.JLabel jLTermo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPPreProcessamento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRBRemDuplicados;
    private javax.swing.JRadioButton jRBRemRT;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFTermo;
    private org.jdesktop.swingx.JXButton jXBPreProcessar;
    private org.jdesktop.swingx.JXButton jXBSair;
    private org.jdesktop.swingx.JXTable jXTTermos;
    // End of variables declaration//GEN-END:variables
}
