/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package captura.view;

import java.awt.event.KeyEvent;
import java.io.File;
import javax.swing.JOptionPane;
import captura.control.ControladorFiltroStreamView;
import captura.control.ControladorStream;
import utilitarios.ArrayUtils;
import exceptions.ArquivoExistenteException;
import exceptions.ErroInternoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import utilitarios.ArquivoUtils;

/**
 *
 * @author W8
 */
public class FiltroStreamTweetsView extends javax.swing.JDialog {

    private TableModelTabelaTermos tableTermos;

    /**
     * Creates new form CapturadorView
     *
     * @param parent
     * @param modal
     */
    public FiltroStreamTweetsView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setResizable(false);
        verificarNumeroCaracteresRestantes();
        jTFTermo.setDocument(new utilitarios.LimitaNroCaracteres(140));
        setarTableModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPCapturador = new javax.swing.JPanel();
        jPTermos = new javax.swing.JPanel();
        jTFTermo = new javax.swing.JTextField();
        jLTermo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jXTTermos = new org.jdesktop.swingx.JXTable();
        jLNumChar = new javax.swing.JLabel();
        jXBCapturar = new org.jdesktop.swingx.JXButton();
        jXBCancelar = new org.jdesktop.swingx.JXButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPCapturador.setBackground(new java.awt.Color(255, 255, 255));

        jPTermos.setBackground(new java.awt.Color(255, 255, 255));
        jPTermos.setBorder(javax.swing.BorderFactory.createTitledBorder("Termos"));

        jTFTermo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFTermoFocusGained(evt);
            }
        });
        jTFTermo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFTermoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFTermoKeyReleased(evt);
            }
        });

        jLTermo.setText("Termo:");

        jXTTermos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jXTTermos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jXTTermosKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jXTTermos);

        jLNumChar.setForeground(new java.awt.Color(51, 102, 255));
        jLNumChar.setText("140");

        javax.swing.GroupLayout jPTermosLayout = new javax.swing.GroupLayout(jPTermos);
        jPTermos.setLayout(jPTermosLayout);
        jPTermosLayout.setHorizontalGroup(
            jPTermosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTermosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPTermosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPTermosLayout.createSequentialGroup()
                        .addComponent(jLTermo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFTermo, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLNumChar))
                    .addComponent(jScrollPane2))
                .addGap(0, 0, 0))
        );
        jPTermosLayout.setVerticalGroup(
            jPTermosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTermosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPTermosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFTermo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTermo)
                    .addComponent(jLNumChar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jXBCapturar.setBackground(new java.awt.Color(255, 255, 255));
        jXBCapturar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jXBCapturar.setText("Capturar");
        jXBCapturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXBCapturarActionPerformed(evt);
            }
        });

        jXBCancelar.setBackground(new java.awt.Color(255, 255, 255));
        jXBCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jXBCancelar.setText("Cancelar");
        jXBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXBCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPCapturadorLayout = new javax.swing.GroupLayout(jPCapturador);
        jPCapturador.setLayout(jPCapturadorLayout);
        jPCapturadorLayout.setHorizontalGroup(
            jPCapturadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCapturadorLayout.createSequentialGroup()
                .addGroup(jPCapturadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPTermos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPCapturadorLayout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jXBCapturar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jXBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPCapturadorLayout.setVerticalGroup(
            jPCapturadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCapturadorLayout.createSequentialGroup()
                .addComponent(jPTermos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPCapturadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXBCapturar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPCapturador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPCapturador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jXBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXBCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jXBCancelarActionPerformed

    private void jTFTermoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFTermoFocusGained
        jTFTermo.selectAll();
    }//GEN-LAST:event_jTFTermoFocusGained

    private void jTFTermoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFTermoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            adicionarTermo(jTFTermo.getText());
            jTFTermo.setText("");
            jTFTermo.requestFocus();
        }
    }//GEN-LAST:event_jTFTermoKeyPressed

    private void jXTTermosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jXTTermosKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            Object[] options = new Object[]{"Sim", "Não"};
            int r = JOptionPane.showOptionDialog(null, "Deseja excluir o termo " + tableTermos.getTermo(jXTTermos.getSelectedRow()) + "?", "Confirmação",
                    JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, 0);
            if (r == 0) {
                tableTermos.removeRow(jXTTermos.getSelectedRow());
            }
        }
    }//GEN-LAST:event_jXTTermosKeyPressed

    private void jTFTermoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFTermoKeyReleased
        verificarNumeroCaracteresRestantes();
    }//GEN-LAST:event_jTFTermoKeyReleased

    private void jXBCapturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXBCapturarActionPerformed
        try {
            File arquivo = ArquivoUtils.abrirFileChooserSalvarArquivo(".txt");
            String[] filtros = ArrayUtils.transformarArrayListemArray(tableTermos.getTermos());
            ControladorStream.salvarArquivoTermos(arquivo, filtros);
            ControladorFiltroStreamView.irParaTelaCaptura(arquivo, filtros);
        } catch (ErroInternoException ex) {
            ex.exibirMensagemAoUsuario(ex);
        } catch (IndexOutOfBoundsException ex) {
            new ErroInternoException().exibirMensagemAoUsuario(ex);
        } catch (ArquivoExistenteException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Aviso", JOptionPane.WARNING_MESSAGE);
        } catch (ArquivoUtils.ArquivoNaoSalvoException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jXBCapturarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FiltroStreamTweetsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FiltroStreamTweetsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FiltroStreamTweetsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FiltroStreamTweetsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            FiltroStreamTweetsView dialog = new FiltroStreamTweetsView(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLNumChar;
    private javax.swing.JLabel jLTermo;
    private javax.swing.JPanel jPCapturador;
    private javax.swing.JPanel jPTermos;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFTermo;
    private org.jdesktop.swingx.JXButton jXBCancelar;
    private org.jdesktop.swingx.JXButton jXBCapturar;
    private org.jdesktop.swingx.JXTable jXTTermos;
    // End of variables declaration//GEN-END:variables

    private void verificarNumeroCaracteresRestantes() {
        String termo = jTFTermo.getText();
        int tam = termo.length();
        int restante = 140 - tam;
        jLNumChar.setText(String.valueOf(restante));
    }

    private void adicionarTermo(String termo) {
        if (!termo.isEmpty()) {
            tableTermos.addRow(termo);
        } else {
            JOptionPane.showMessageDialog(null, "Informe o termo!", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void setarTableModel() {
        tableTermos = new TableModelTabelaTermos(jXTTermos);
        jXTTermos.setModel(tableTermos);
    }

}
