/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import static classifica.Classifica.classificar;
import tarefas_as.subjetividade.view.ClassificacaoSubjetividadeView;
import exceptions.DadoInvalidoException;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import tweet.Tweet;
import utilitarios.ClasseUtilitaria;
import exceptions.ErroInternoException;
import sumarizacao.SumarizacaoView;
import utilitarios.ArquivoUtils;

/**
 *
 * @author Arthur Caique
 */
public class ASView extends javax.swing.JFrame {

    /**
     * Creates new form ASView
     *
     * @param parent
     * @param modal
     */
    public ASView(java.awt.Frame parent, boolean modal) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPAS = new javax.swing.JPanel();
        jBSub = new org.jdesktop.swingx.JXButton();
        jXButton2 = new org.jdesktop.swingx.JXButton();
        jXButton3 = new org.jdesktop.swingx.JXButton();
        jXButton4 = new org.jdesktop.swingx.JXButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tarefas da Análise de Sentimento");

        jPAS.setBackground(new java.awt.Color(255, 255, 255));

        jBSub.setBackground(new java.awt.Color(204, 204, 204));
        jBSub.setText("Classificação de Subjetividade");
        jBSub.setFocusPainted(false);
        jBSub.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        jBSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSubActionPerformed(evt);
            }
        });

        jXButton2.setBackground(new java.awt.Color(204, 204, 204));
        jXButton2.setText("Extração de Característica");
        jXButton2.setFocusPainted(false);

        jXButton3.setBackground(new java.awt.Color(204, 204, 204));
        jXButton3.setText("Classificação");
        jXButton3.setFocusPainted(false);
        jXButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton3ActionPerformed(evt);
            }
        });

        jXButton4.setBackground(new java.awt.Color(204, 204, 204));
        jXButton4.setText("Sumarização");
        jXButton4.setFocusPainted(false);

        javax.swing.GroupLayout jPASLayout = new javax.swing.GroupLayout(jPAS);
        jPAS.setLayout(jPASLayout);
        jPASLayout.setHorizontalGroup(
            jPASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPASLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSub, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jPASLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBSub, jXButton2, jXButton3, jXButton4});

        jPASLayout.setVerticalGroup(
            jPASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPASLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jBSub, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jXButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jXButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jXButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jPASLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBSub, jXButton2, jXButton3, jXButton4});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPAS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPAS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSubActionPerformed
        try {
            File arquivo = ArquivoUtils.selecionarArquivo();
            ArrayList<Tweet> tweets = Fachada.getINSTANCIA().recuperarTweets(arquivo);
            ClassificacaoSubjetividadeView subView = new ClassificacaoSubjetividadeView(null, true);
            subView.inserirTweets(tweets);
            ClasseUtilitaria.abrirView(subView, null);
        } catch (ErroInternoException ex) {
            ex.exibirMensagemAoUsuario(ex);
        }  catch (DadoInvalidoException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.ERROR);
        } catch (ArquivoUtils.ArquivoNaoSelecionadoException ex) {
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_jBSubActionPerformed

    private void jXButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton3ActionPerformed
        try {
            JOptionPane.showMessageDialog(null, "Selecionar o modelo!");
            File modelo = ArquivoUtils.selecionarArquivo();
            JOptionPane.showMessageDialog(null, "Selecionar os tweets a serem classificados!");
            File naoClassificado = ArquivoUtils.selecionarArquivo();
            ArrayList<Tweet> classificar = classificar(modelo, naoClassificado);
            sumarizacao.SumarizacaoView view = new SumarizacaoView(null, true);
            view.exibir(naoClassificado.getPath(), classificar);
            ClasseUtilitaria.abrirView(view, null);
        } catch (ErroInternoException ex) {
            ex.exibirMensagemAoUsuario(ex);
        } catch (DadoInvalidoException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (ArquivoUtils.ArquivoNaoSelecionadoException ex) {
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_jXButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ASView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ASView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ASView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ASView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            ASView dialog = new ASView(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXButton jBSub;
    private javax.swing.JPanel jPAS;
    private org.jdesktop.swingx.JXButton jXButton2;
    private org.jdesktop.swingx.JXButton jXButton3;
    private org.jdesktop.swingx.JXButton jXButton4;
    // End of variables declaration//GEN-END:variables
}
